-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 10:11:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema foroGamesHelper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foroGamesHelper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foroGamesHelper` DEFAULT CHARACTER SET utf8 ;
USE `foroGamesHelper` ;

-- -----------------------------------------------------
-- Table `foroGamesHelper`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroGamesHelper`.`usuarios` (
  `id` INT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`usuario`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroGamesHelper`.`juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroGamesHelper`.`juegos` (
  `idjuegos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `compania` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `coop` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idjuegos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroGamesHelper`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroGamesHelper`.`posts` (
  `idposts` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `usuarios_usuario` VARCHAR(45) NOT NULL,
  `usuarios_email` VARCHAR(45) NOT NULL,
  `juegos_idjuegos` INT NULL,
  PRIMARY KEY (`idposts`, `usuarios_usuario`, `usuarios_email`),
  INDEX `fk_posts_usuarios1_idx` (`usuarios_usuario` ASC, `usuarios_email` ASC),
  INDEX `fk_posts_juegos1_idx` (`juegos_idjuegos` ASC),
  CONSTRAINT `fk_posts_usuarios1`
    FOREIGN KEY (`usuarios_usuario` , `usuarios_email`)
    REFERENCES `foroGamesHelper`.`usuarios` (`usuario` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_juegos1`
    FOREIGN KEY (`juegos_idjuegos`)
    REFERENCES `foroGamesHelper`.`juegos` (`idjuegos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroGamesHelper`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroGamesHelper`.`comentarios` (
  `usuarios_usuario` VARCHAR(45) NOT NULL,
  `usuarios_email` VARCHAR(45) NOT NULL,
  `posts_idposts` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  PRIMARY KEY (`usuarios_usuario`, `usuarios_email`, `posts_idposts`),
  INDEX `fk_usuarios_has_posts_posts1_idx` (`posts_idposts` ASC),
  INDEX `fk_usuarios_has_posts_usuarios_idx` (`usuarios_usuario` ASC, `usuarios_email` ASC),
  CONSTRAINT `fk_usuarios_has_posts_usuarios`
    FOREIGN KEY (`usuarios_usuario` , `usuarios_email`)
    REFERENCES `foroGamesHelper`.`usuarios` (`usuario` , `email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_posts_posts1`
    FOREIGN KEY (`posts_idposts`)
    REFERENCES `foroGamesHelper`.`posts` (`idposts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
